name: rogi_le

channels:
  - conda-forge
  - defaults
  - pytorch

dependencies:
  - cudatoolkit=11.3
  - python >= 3.9
  - pytorch::pytorch >=1.10
  - rdkit
  - pip
  - configargparse
  - h5py
  - numpy
  - pytorch-lightning
  - scikit-learn
  - tqdm
