# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev168+g8f17f80.d20230501'
__version_tuple__ = version_tuple = (0, 1, 'dev168', 'g8f17f80.d20230501')
